### ISSUE TITLE
Optional std::iostream?

### ISSUE THREAD

**Issue by stephenberry** [qlibs/ut#1]
This is neat, but I'm curious how the standard library is optional when you have the following code:
```c++
#if __has_include(<iostream>)
#include <iostream> // [optional] std::clog
#endif

#if __has_include(<cstdint>)
#include <cstdint> // [optional] std::int8_t, std::int16_t, std::int32_t, std::int64_t, std::uint8_t, std::uint32_t, std::uint64_t
#endif
```

These `__has_include` checks will return true on compilers with these headers. So, I understand how they are optional in the sense that `ut2` could be used on a platform without these headers, but it doesn't seem to be optional to avoid including these headers on a typical C++ compiler, as they will always return true.

Could there be a way to make them optional (configurable) for common C++ compilers?

**Comment by kris-jusiak** [comment]
`-DUT2_HAS_IOSTREAM=false` should do the trick

**Comment by stephenberry** [comment]
Sweet, thanks!
